### ISSUE TITLE
Issues (potential blockers but not only)

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-docker#1]
- [x] https://github.com/OpenVoiceOS/ovos-messagebus/issues/4
- [ ] https://github.com/OpenVoiceOS/ovos-listener/issues/15
- [x] https://github.com/OpenVoiceOS/OVOS-workshop/issues/67
- [x] https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/issues/82
- [ ] https://github.com/OpenVoiceOS/ovos-listener/issues/16

**Comment by JarbasAl** [comment]
last one should not be a blocker, but solved by https://github.com/OpenVoiceOS/OVOS-workshop/pull/72

**Comment by JarbasAl** [comment]
https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin/issues/82  is padatious matching the wrong intent, this is not an issue with docker but a general problem with mycroft

padatious intents are not deterministic and will depend on the number of skills installed also using padatious intents, once you have all skills installed hopefully disambiguation will become better and lower the confidence of that match

**Comment by goldyfruit** [comment]
Closing as not really useful anymore.
