### ISSUE TITLE
Broken Links in README

### ISSUE THREAD

**Issue by ghost** [OpenVoiceOS/ovos-docker#13]
The bold/italics links are broken.

Open Voice OS running on Docker or Podman
         _**What is Open Voice OS?**_
         _**How does it work with Docker or Podman?**_
       
Supported architectures and tags
             Architectures
             Hardware tested on
             _**Operating systems (64-bit version) tested on**_
            
How to build these images
         Arguments
         Image alternatives
         Message bus
         _**Listener**_
        
_**TTS (Text-to-Speech) and STT (Speech-to-Text)**_

**Comment by goldyfruit** [comment]
Fixed :+1:
