### ISSUE TITLE
Manifest Unknown Error

### ISSUE THREAD

**Issue by ghost** [OpenVoiceOS/ovos-docker#21]
When downloading the base image via `docker pull` command, I get the error `Error response from daemon: manifest for smartgic/ovos-base:latest not found: manifest unknown: manifest unknown`

https://hub.docker.com/r/smartgic/ovos-base is the one I tried since all other images rely on the base. I haven't tried others.

**Comment by goldyfruit** [comment]
@generallynonsensical according [to the documentation](https://github.com/OpenVoiceOS/ovos-docker#tags), there is no _(yet)_ the `latest` tag as there is not `stable` release.

I would recommend to use the `alpha` tag.

FYI, the `ovos-base` image almost contains nothing as it's only related to the main Python version.
