### ISSUE TITLE
mount log folder for ease of log management

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker#22]
Mounting the logs folders can make it easier to debug sometimes, or follow what is going on. furthermore, a rotation can be put in place on the docker machine to manage the space

**Comment by goldyfruit** [comment]
When using Docker, you should not have logs into the containers as they are identical with what is already available in the `stdout`.

To avoid the log to be created by the service, you should add this to your `mycroft.conf`:
```json
  "logs": {
    "path": "stdout"
  }
```

From the `README.md`:

![image](https://github.com/OpenVoiceOS/ovos-docker/assets/614115/364cce16-4917-4b55-810d-c26baf56ed1f)


If you need to get all the logs from the containers, you can run `docker compose logs`:
```shell
docker compose -f docker-compose.yml -f docker-compose.skills.yml --env-file .env logs -n -f --tail 200
```

And the best practice to log containers `stdout` would be to use a log aggregator such as Filebeat _(but that could be a bit over kill, depends of your needs)_.

**Comment by denics** [comment]
then probably I did something wrong as in my MBP arm64 the ``stdout`` does not work with an error message :(

```
xxx@xxx ~/Git/ovos/ovos-docker/compose (dev*) $ docker exec -it ovos_cli ovos-cli-client


Traceback (most recent call last):
  File "/home/ovos/.venv/bin/ovos-cli-client", line 33, in <module>
    sys.exit(load_entry_point('ovos-cli-client==0.0.1a1', 'console_scripts', 'ovos-cli-client')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_cli_client/__main__.py", line 63, in main
    for f in os.listdir(log_dir):
             ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'stdout'
```

**Comment by goldyfruit** [comment]
> then probably I did something wrong as in my MBP arm64 the `stdout` does not work with an error message :(
> 
> ```
> xxx@xxx ~/Git/ovos/ovos-docker/compose (dev*) $ docker exec -it ovos_cli ovos-cli-client
> 
> 
> Traceback (most recent call last):
>   File "/home/ovos/.venv/bin/ovos-cli-client", line 33, in <module>
>     sys.exit(load_entry_point('ovos-cli-client==0.0.1a1', 'console_scripts', 'ovos-cli-client')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_cli_client/__main__.py", line 63, in main
>     for f in os.listdir(log_dir):
>              ^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'stdout'
> ```

Yeah, you are facing this issue https://github.com/OpenVoiceOS/ovos-cli-client/issues/12 which is related to `ovos-cli`, and `ovos-cli` is not really maintained anymore.

**Comment by goldyfruit** [comment]
I just pushed this [commit](https://github.com/OpenVoiceOS/ovos-docker/commit/03a644a1c6f96f25f781cc02020d6439f7b93ccf) to avoid this error, not pretty but its working.
