### ISSUE TITLE
how to locally host mimic3 or piper?

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker#26]
using ovos-docker what is the best way to run its self hosted TTS / STT ?

**Comment by goldyfruit** [comment]
You can have a look to this repo https://github.com/OpenVoiceOS/ovos-docker-tts to install a self-hosted containerised TTS _(the repository is not yet public but I added you so you should have a read access)_. 

I have to write the `README` for this repo.

```shell
mkdir -p ~/ovos-tts-stt/config
docker compose up -d ovos_tts_piper
```

Here is the content of `~/ovos-tts-stt/config/mycroft.conf` for the TTS configuration

```json
{
  "tts": {
    "ovos-tts-plugin-piper": {
      "voice": "amy-low"
    },
    "ovos-tts-plugin-mimic3": {
      "voice": "en_UK/apope_low"
    }
  }
}
```

**Comment by goldyfruit** [comment]
For the STT you could have a look here https://github.com/OpenVoiceOS/ovos-docker-stt _(this one is public)_, there is a documentation in there.

**Comment by goldyfruit** [comment]
Feel free to re-open if needed. :+1:
