### ISSUE TITLE
Installing skill_ovos_fallback_chatgpt fails

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker#29]
when adding ``skill_ovos_fallback_chatgpt`` to the ``skills.list`` file, the installation fails because of a missing translate plugin. This is related to https://github.com/OpenVoiceOS/skill-ovos-fallback-chatgpt/issues/8.

To solve it just install ``neon-lang-plugin-libretranslate`` by adding it to the ``skills.list`` file.

**Comment by denics** [comment]
Just a note in case somebody wonder why it does not work :D

**Comment by goldyfruit** [comment]
@JarbasAl ^

**Comment by goldyfruit** [comment]
Should not be an issue anymore: https://github.com/OpenVoiceOS/ovos-docker/commit/3eab890c1becd3ca3823ef4eb87502ae03ab17ad
