### ISSUE TITLE
Error when running ovos-cli-client

### ISSUE THREAD

**Issue by atd** [OpenVoiceOS/ovos-docker#3]
In a fresh install, when trying to run `ovos-cli-client` in `ovos_cli` I get the following error:

```
Traceback (most recent call last):                                                     
  File "/home/ovos/.venv/bin/ovos-cli-client", line 33, in <module>
      sys.exit(load_entry_point('ovos-cli-client==0.0.1', 'console_scripts', 'ovos-cli-client')())                                                                              
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_cli_client/__main__.py", line 63, in main                                                                          
    for f in os.listdir(log_dir):                                                      
             ^^^^^^^^^^^^^^^^^^^                                                       
FileNotFoundError: [Errno 2] No such file or directory: '/home/ovos/.local/state/mycroft'
```

This is solved by running `mkdir -p /home/ovos/.local/state/mycroft` in the `ovos_cli` container

Maybe it could be worth to create `/home/ovos/.local/state/mycroft` in https://github.com/OpenVoiceOS/ovos-docker/blob/dev/cli/Dockerfile ?

**Comment by goldyfruit** [comment]
@atd I raised this issue here https://github.com/OpenVoiceOS/ovos-cli-client/issues/12 but then there is [the potential "abandon"](https://github.com/OpenVoiceOS/ovos-cli-client/issues/14) of this CLI for Neon MANA.

I guess for now we can create these folders within the image. :+1:

**Comment by goldyfruit** [comment]
Let me know.

![image](https://user-images.githubusercontent.com/614115/235565454-2ce29587-f421-4886-a9e3-0f6696963975.png)

```
ovos@ovos_cli:~$ ls -la .local/state/mycroft/
total 8
drwxr-xr-x 2 ovos ovos 4096 May  1 22:13 .
drwxr-xr-x 3 ovos ovos 4096 May  1 22:13 ..
```

**Comment by goldyfruit** [comment]
Closing for now, feel free to re-open if you still have the issue. :+1:

**Comment by atd** [comment]
That was quick! I will let you know. Thank you @goldyfruit !
