### ISSUE TITLE
Wayland and GUI

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker#30]
Is it possible to run the GUI when using Wayland? if this is the case, can we have a section in the README?

**Comment by goldyfruit** [comment]
I guess it will depends of the GPU.

**Comment by goldyfruit** [comment]
Wayland will work for sure but maybe not with hardware acceleration.

**Comment by goldyfruit** [comment]
I'll close it for now as the status of the GUI still in progress in `ovos-docker`.
