### ISSUE TITLE
sdnotify (READY) support

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-docker#32]
I am in progress (learning howto) to create and run the containers fully under systemd by utilizing the quadlets system which is part of Podman >4.4

One of the benefits of it is to use the sdnotify system to let systemd know when a started container is fully loaded and ready. 

"--sdnotify=container" instead of "--sdnotify=conmon"

For this to work, we need to use the systemd wrappers as start entry point within the containers. As there is no downside of using the wrappers while not using the sdnotify system itself, I would like to ask to make it the default entry point such that I can just pull the images from the registry instead of building them myself.

**Comment by goldyfruit** [comment]
I'll have to check but I don't think `sdnotify` is supported by Docker.

**Comment by goldyfruit** [comment]
Did some research and indeed, `--sdnotify` is not supported by Docker.

`--sdnotify` seems to be by default set with `container`.

```shell
podman inspect ovos_stt_fasterwhisper | jq .[].Config.sdNotifyMode
"container"
```

Did you run as well the `podman generate systemd` command?

```shell
podman generate systemd --new -n -f --start-timeout 600 ovos_stt_fasterwhisper
```

**Comment by j1nx** [comment]
For podman systemd integration having the ovos service reporting back that it is ready to rock and roll, we need to include the systemd wrappers within the containers and change the entry points to use them.

https://github.com/OpenVoiceOS/ovos-buildroot/tree/5c7af8b05892206846ae06adb3478f1df620bf6b/buildroot-external/rootfs-overlay/base/usr/libexec

You need the mycroft-systemd-* files.

-----------

As example for the messagebus service, instead of having the ENTRYPOINT = "ovos-messagebus" we will have to change the entry point to; calling that wrapper file  "mycroft-systemd-messagebus".

It does the same, starting the messagebus service, houwever really sending the sdnotify READY back to the system.

That way we can use the --sdnotify=container podman flag to let systemd know the service itself is fully ready, instead of the container has been launched. (the container could be launched but system will otherwise not know if the messagebus itself is also fully started/ready)

**Comment by goldyfruit** [comment]
I think these files should be part of a Python package on PyPi and renamed to ovos.

What do you think?

**Comment by builderjer** [comment]
all of the systemd hook files on PyPi?  That would make things easy

**Comment by j1nx** [comment]
Agree! Will ping @JarbasAl for when he is back from holidays.

**Comment by JarbasAl** [comment]
> all of the systemd hook files on PyPi? That would make things easy

i dont mind adding those entrypoints to the repos, but sdnotify should not be a hard dependency (as we want to support non systemd services too), either add a new entrypoint or make the sdnotify import optional in the main entrypoints (use it if its there else ignore)

**Comment by builderjer** [comment]
That would probably be the quickest way to make it optional for sure.

**Comment by goldyfruit** [comment]
> > all of the systemd hook files on PyPi? That would make things easy
> 
> i dont mind adding those entrypoints to the repos, but sdnotify should not be a hard dependency (as we want to support non systemd services too), either add a new entrypoint or make the sdnotify import optional in the main entrypoints (use it if its there else ignore)

I think we should have a dedicated repo for these files.

**Comment by j1nx** [comment]
I once made this;
https://github.com/j1nx/mycroft-systemd

I could transfer it so we can bump/ change the files.

**Comment by goldyfruit** [comment]
> I once made this; https://github.com/j1nx/mycroft-systemd
> 
> I could transfer it so we can bump/ change the files.

Yeah and maybe build a PyPi package based on specific directory.

**Comment by builderjer** [comment]
That's what I was thinking when I looked also.

**Comment by j1nx** [comment]
Here we go!

https://github.com/OpenVoiceOS/ovos-systemd

No clue about PyPi packaging but gave access to any distro admin, so we should be able to get it up to date.

**Comment by j1nx** [comment]
@builderjer Did you started the work on the systemd wrappers already?

I just discovered that for the auto-update/rollback feature of podman it actually needs the "sdnotify=container" flag as the rollback uses it to determine if the update was succesfull or not.

**Comment by j1nx** [comment]
Not entirely true anymore;
https://github.com/containers/podman/pull/19353

Looks like we can also use the healthy checks now to report back to systemd. Will do some testing with it.

**Comment by builderjer** [comment]
I did start on it, but cloned from ovos repo instead of forking my own.  Now I see I dont have permissions there

**Comment by goldyfruit** [comment]
@j1nx  what happens if `systemd` is not running on the system *(like SysV is running instead)*?

**Comment by goldyfruit** [comment]
I'll close this issue as for now this will not be implemented.
