### ISSUE TITLE
cannot play start_listening

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-docker#34]
I don't know if it is a bug or if it is my configuration, but I am unable to play the ``start_listening`` sound when using ovos_docker. Audio works fine in TTS / STT / LISTENER . Any hint?

This is the configuration:

```json
{
  'start_listening': 'snd/start_listening.wav', 
  'end_listening': 'snd/end_listening.wav', 
  'acknowledge': 'snd/acknowledge.mp3', 
  'error': 'snd/error.mp3'
}
```
found in /sounds

and the files exists: 

```sh
[12:58:12] ~/Git/ovos/ovos-docker/compose $ docker exec -it ovos_core bash
ovos@ovos_core:~$ paplay ./.venv/lib/python3.11/site-packages/mycroft/res/snd/start_listening.wav
```

**Comment by j1nx** [comment]
I believe I have the same issue.

During all my test and dev work I also never hear the listener confirmation sound, however have not yet paid attention to it as I am still busy with other things...

**Comment by goldyfruit** [comment]
Try with the absolute path.

```json
  "sounds": {
    "start_listening": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/start_listening.wav",
    "end_listening": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/end_listening.wav",
    "acknowledge": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/acknowledge.mp3"
  },
```

https://github.com/OpenVoiceOS/ovos-listener/issues/10

**Comment by j1nx** [comment]
Which container should play the sound? Listerner, core or audio?

**Comment by goldyfruit** [comment]
> Which container should play the sound? Listerner, core or audio?

Listener, until https://github.com/OpenVoiceOS/ovos-utils/pull/188 got merged

**Comment by j1nx** [comment]
Ah, great. Knew I read something about it. Thx for the link.

@denics You logged into the weong container as you appear to be logging into the core container in your test above.

**Comment by denics** [comment]
Should this be added to documentation? or provided into a mini default ``mycroft.conf`` ?

**Comment by goldyfruit** [comment]
> Should this be added to documentation? or provided into a mini default `mycroft.conf` ?

This is mostly a bug that should be fixed in `dinkum-listener`. I'll add a link to the [FAQ](https://github.com/OpenVoiceOS/ovos-docker#faq) section pointing to this issue.

@JarbasAl you were assigned to this with the "legacy" listener https://github.com/OpenVoiceOS/ovos-listener/issues/10 any idea on how to fix it?

**Comment by denics** [comment]
> ```json
> "sounds": {
>     "start_listening": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/start_listening.wav",
>     "end_listening": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/end_listening.wav",
>     "acknowledge": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/acknowledge.mp3"
>   },
> ```

I confirm this solves the issue on a docker installation.
